/*-------------------------------------------------------------*
 * THIS FILE IS AUTO-GENERATED BY EMGEN, DO NOT COMMIT OR EDIT *
 *-------------------------------------------------------------*/

var messages = {};
messages.index = [];

var bufferList = [];
var maxBufferSize = 128000;

var convertBuffer = new ArrayBuffer(8);
var floatArray = new Float32Array(convertBuffer);
var intArray = new Uint16Array(convertBuffer);

function getBuffer() {
    if( bufferList.length == 0 )
    {
        return new Buffer(maxBufferSize);
    }

    return bufferList.pop();
}
messages.getBuffer = getBuffer;

function returnBuffer(buffer) {
    if( buffer )
    {
        bufferList.push(buffer);
    }
}
messages.returnBuffer = returnBuffer;

function MessagePrototype(name, id) {
    this.name = name;
    this.id = id;
};

MessagePrototype.prototype.store = function(buffer) {
    this.buffer = buffer || getBuffer();
    this.bufferOwned = true;
    if( buffer )
    {
        this.bufferOwned = false;
    }
};

MessagePrototype.prototype.retain = function() {
    if( this.references === undefined )
    {
        this.references = 1;
    }
    else
    {
        this.references++;
    }
};

MessagePrototype.prototype.release = function() {
    if( this.references === undefined && this.bufferOwned )
    {
        returnBuffer(this.buffer);
    }
    else
    {
        this.references--;
        if( this.references <= 0 && this.bufferOwned )
        {
            returnBuffer(this.buffer);
        }
    }
};

