/*-------------------------------------------------------------*
 * THIS FILE IS AUTO-GENERATED BY EMGEN, DO NOT COMMIT OR EDIT *
 *-------------------------------------------------------------*/

function NetworkMessageManager() {
    this.index = [];

    this.bufferList = [];
    this.maxBufferSize = 128000;
}

NetworkMessageManager.prototype = {
    getBuffer: function() {
        if( this.bufferList.length == 0 )
        {
            return new ArrayBuffer(this.maxBufferSize);
        }

        return this.bufferList.pop();
    },

    returnBuffer: function(buffer) {
        if( buffer )
        {
            this.bufferList.push(buffer);
        }
    }
}

var messageManager = new NetworkMessageManager();
var module = module || undefined;
if( module && module.exports )
{
    module.exports = messageManager;
}