/*-------------------------------------------------------------*
 * THIS FILE IS AUTO-GENERATED BY EMGEN, DO NOT COMMIT OR EDIT *
 *-------------------------------------------------------------*/

var messages = {};
messages.index = [];

var bufferList = [];
var maxBufferSize = 128000;

function getBuffer() {
    if( bufferList.length == 0 )
    {
        return new Buffer(maxBufferSize);
    }

    return bufferList.pop();
}
messages.getBuffer = getBuffer;

function returnBuffer(buffer) {
    if( buffer )
    {
        bufferList.push(buffer);
    }
}
messages.returnBuffer = returnBuffer;

